### ISSUE TITLE
TODO First deadline

### ISSUE THREAD

**Issue by TheoVerhelst** [TheoVerhelst/DocHub#1]
The system of group has already been implemented by the DocHub team, but it is mainly oriented on documents sharing. We want to focus more on the chat and forum aspects.

### Telepathy
Currently, DocHub has a messaging system that is solely based on threads/replies to the thread. They called this system *telepathy*, and it is located in the eponymous directory.  
Globally, the telepathy app seems to be well designed in its model, but the views and templates don't really fit what we want. So I propose to keep the telepathy code, and just tweak what we need in order to get the result we want.

### The list
**We should assign ourselves to a specific task so that we can focus on one thing, otherwise we will never start the work.**  
I assigned myself to the 6th point.
* [x] Creation and deletion of groups (assignee @StanIsAdmin)
* [x] Joining to a group
* [x] Add a thread of discussion to a group, reply on this thread
* [ ] Delete a thread or a specific message
* [x] The chat
* [x] Change the design of `templates/catalog/groups.html` to focus more on messages than documents
* [x] Make the message writing/editing on the same page as the thread view (like in Facebook groups)

### Concretely, the implementation
Here are what I think about the implementation of the points in the list:
1. *Creation and deletion of groups:* New view in catalogs/views.py, and new corresponding templates. Look at telepathy messages forms for clues on how to write them.
2. *Joining to a group* and 3. *Add a thread of discussion* has already been made by the DocHub team.

4. *Delete a thread or a specific message* This is just a button on the thread template, and the corresponding view in telepathy.
5. *The chat* Either this is a new app, either this is just more model/view/templates in telepathy. I don't know which to choose.
6. *Change the design of `templates/catalog/groups.html`* Well, I'm working on it, it's the easiest point.
7. *Make the message writing/editing on the same page* I think the telepathy form template should be included in the thread view, and some views will need to be tweaked.
